### ISSUE TITLE
Studio: migrate Working with Enumerations section

### ISSUE THREAD

**Issue by alexbudarov** [jmix-framework/jmix-v1-v2-docs#100]
From: https://doc.cuba-platform.com/studio/#data_model_enums

No significant content changes expected.

To:
Let's put it straight to the end of https://docs.jmix.io/jmix/0.x/data-model/enumerations.html section.
Add TOC to this article.

Add link from Tool Window to this new section.

**Comment by zhenyazb** [comment]
fixed in #361
