### ISSUE TITLE
Studio - mention application URL in terminal

### ISSUE THREAD

**Issue by alexbudarov** [jmix-framework/jmix-v1-v2-docs#156]
see implemented Studio ticket: https://youtrack.jmix.io/issue/JST-203

Section  - https://docs.jmix.io/jmix/0.x/studio/project.html#_starting_application

1) re-shot screenshot after "See the status in the Console tab of the Debug tool window."
2) change text after. User can click the link in the console after the application is started.

**Comment by zhenyazb** [comment]
fixed in #361
