### ISSUE TITLE
Update "Create REST enabled Role" section

### ISSUE THREAD

**Issue by alexbudarov** [jmix-framework/jmix-v1-v2-docs#158]
https://docs.jmix.io/jmix/0.x/rest/quick-start.html#_create_rest_enabled_role

After https://github.com/Haulmont/jmix-rest/issues/32 was implemented, not there is no need to create own role with "rest.enabled" permission.
Just assign this role to admin or other user that you want to use.

**Comment by mariodavid** [comment]
see: https://github.com/Haulmont/jmix-docs/issues/158
