### ISSUE TITLE
Exclude Quartz table names from liquibase processing

### ISSUE THREAD

**Issue by gorbunkov** [jmix-framework/jmix-v1-v2-docs#177]
When some add-on requires Quartz, we suggest to add Quartz starter to the project. See https://docs.jmix.io/jmix/0.x/email/configuration.html#quartz
The problem is that Quartz creates database tables. On the next project start in Studio, Studio tries to remove quartz database tables.
The solution is to add application property which excludes quartz tables from liquibase processing:
```
main.datasource.studio.liquibase.excludePrefixes = qrtz_
```
See https://youtrack.haulmont.com/articles/PLAT-A-189/Jmix-Liquibase

**Comment by knstvk** [comment]
See #235
