### ISSUE TITLE
Add /latest/ URL to access the docs

### ISSUE THREAD

**Issue by alexbudarov** [jmix-framework/jmix-v1-v2-docs#224]
We need to be able to publish https://docs.jmix.io/jmix/1.0/studio/subscription.html link (e.g. in Store's email templates)
like https://docs.jmix.io/jmix/latest/studio/subscription.html
to automatically use latest available documentation version.

**Comment by knstvk** [comment]
Now https://docs.jmix.io/jmix/latest/* redirects to https://docs.jmix.io/jmix/1.0/*
