### ISSUE TITLE
Describe DataContext events and delegates

### ISSUE THREAD

**Issue by alexbudarov** [jmix-framework/jmix-v1-v2-docs#234]
https://docs.jmix.io/jmix/1.0/backoffice-ui/data/data-context.html

Events and delegates of DataContext aren't described in the documentation at the moment.

E.g. when you talk about implementing standard screens for DTO entities - you need to implement a commitDelegate of the dataContext.
![datacontext](https://user-images.githubusercontent.com/6158807/128142260-814e7877-e836-46bd-be1f-2f67e530accd.png)

**Comment by oshiryaeva** [comment]
@alexbudarov please check if that's enough
