### ISSUE TITLE
Search: minor improvements

### ISSUE THREAD

**Issue by Gavrilov-Ivan** [jmix-framework/jmix-v1-v2-docs#249]
- https://docs.jmix.io/jmix/search/getting-started.html#_test_searching_in_application: Screenshot of search result screen has bad looking names of the records. Instance Name is used as a name of record and it seems it is not configured for Order entity used in this example. 
Screenshot should be taken after configuration of Instance Name and instances reindexing (because its value is stored in index too).
Also it will be good to mention this point - names of records on search result screen are their Instance Names.
- https://docs.jmix.io/jmix/search/index-definitions.html#reference-attributes: fix JSON formatting
- https://docs.jmix.io/jmix/search/search-in-ui.html#using-search-api-in-screens: add a little more details in (2) note (or split it)
  - setSize - describe what default value is 10 (and use another value in example)
  - setEntities - describe what this is the list of entities within which search will be performed (all indexed entities by default)

**Comment by oshiryaeva** [comment]
Size M because of [this issue](https://github.com/jmix-framework/jmix/issues/624)
