### ISSUE TITLE
Actualize and fix code example in Creating Calculated Attribute

### ISSUE THREAD

**Issue by owlet1997** [jmix-framework/jmix-v1-v2-docs#26]
### Enviroment:
Part of the documentation: quick start
Existing page: https://docs.jmix.io/jmix/0.x/quick-start/index.html

### Description of the bug or enchacement
§Creating Calculated Attribute

1. Different name of function in text and in example of code:
*Text:*
To do this, we need to create a new method - **getFullName()** in the Speaker class and make its return type String.

*Code:*
```
@InstanceName
@DependsOnProperties({"firstName", "lastName", "username"})
public String getDisplayName() {
    return String.format("%s %s [%s]", (firstName != null ? firstName : ""),
            (lastName != null ? lastName : ""), username);
}
```
*AR:* different names of function
*ER:* function should have one name in text and in example

2. There is no field 'username" in class Speaker which used in this function (p.1)
Listing of class (getters, setters and imports are omitted):
```
package com.company.jmixpr.entity;
@JmixEntity
@Table(name = "JMIXPR_SPEAKER")
@Entity(name = "jmixpr_Speaker")
public class Speaker {
    @JmixGeneratedValue
    @Column(name = "ID", nullable = false)
    @Id
    private UUID id;

    @Column(name = "FIRST_NAME", nullable = false)
    @NotNull
    private String firstName;

    @Column(name = "LAST_NAME")
    private String lastName;

    @Email
    @Column(name = "EMAIL", nullable = false, length = 1024)
    @NotNull
    private String email;
}
```
*AR:* non-existing field in function
*ER:* function should use only existing fields

**Comment by zhenyazb** [comment]
Fixed in #75
