### ISSUE TITLE
Wrong information about debug configuration settings

### ISSUE THREAD

**Issue by alexbudarov** [jmix-framework/jmix-v1-v2-docs#264]
https://docs.jmix.io/jmix/studio/project.html#_rundebug_configuration_settings

> You might be interested in editing the following settings:
Arguments – JVM options to be passed to the debug server. For example, specify -Xmx1500m to increase maximum allowed memory usage for the server.
Environment variables – environment variables that should be available to the debug server process.

This is wrong. Parameters are passed to Gradle process, not to the running app.

see https://forum.jmix.io/t/add-java-opts-in-idea-at-runtime/529

**Comment by zhenyazb** [comment]
fixed in #361
