### ISSUE TITLE
Actualize and fix example in Creating Data Model

### ISSUE THREAD

**Issue by owlet1997** [jmix-framework/jmix-v1-v2-docs#27]
### Enviroment:
Part of the documentation: quick start
Existing page: https://docs.jmix.io/jmix/0.x/quick-start/index.html

### Description of the bug or enchacement
§Creating Data Model

1. There is too many symbols for field 'email' in example:
![image](https://user-images.githubusercontent.com/45730069/107326631-32e67e00-6ac5-11eb-8d8c-59dc52ce2634.png)

*AR:* length of field is 1024
*ER:* length of field should be equal or less than 256 symbols

**Comment by alexbudarov** [comment]
Resolution:
Change this field to `String(255)`
Large length for email doesn't make sense.

**Comment by zhenyazb** [comment]
Fixed in #75
