### ISSUE TITLE
Document creating a root screen with the route path available for the anonymous user 

### ISSUE THREAD

**Issue by sukhova** [jmix-framework/jmix-v1-v2-docs#271]
See the NOTE:
https://doc.cuba-platform.com/manual-7.2/url_routing.html

![изображение.png](https://images.zenhubusercontent.com/5b360034b46294032187ed9d/1d32bb23-0862-433a-8ba7-d290396fb32a)

**Comment by knstvk** [comment]
See also https://forum.jmix.io/t/how-can-i-verify-and-use-the-anonymous-user-functionality/938/3
