### ISSUE TITLE
How to use MessageBundle in screens

### ISSUE THREAD

**Issue by gorbunkov** [jmix-framework/jmix-v1-v2-docs#325]
Inside screen controllers the `io.jmix.ui.screen.MessageBundle` interface can be used for getting messages from a message group bound to the screen controller.

This probably may be mentioned [here](https://docs.jmix.io/jmix/localization/message-bundles.html#using-messages-in-ui).

**Comment by oshiryaeva** [comment]
https://upsource-platform.haulmont.com/jmix-docs/review/JD-CR-70
