### ISSUE TITLE
Document possibility to map one LDAP group name to resource and row-lewel roles simultaneously 

### ISSUE THREAD

**Issue by artemy63** [jmix-framework/jmix-v1-v2-docs#342]
After changes in Haulmont/jmix-ldap#11 and Haulmont/jmix-ldap#12 it is possible to map one LDAP group name to some resource and role-lewel roles at the same time. 
See https://github.com/Haulmont/jmix-ldap/blob/master/ldap/src/main/java/io/jmix/ldap/userdetails/JmixLdapGrantedAuthoritiesMapper.java#L97-L112

**Comment by zhenyazb** [comment]
fixed in #343
