### ISSUE TITLE
Describe @ReplaceEntity annotation

### ISSUE THREAD

**Issue by owlet1997** [jmix-framework/jmix-v1-v2-docs#371]
In CUBA it was called `@Extends` 
CUBA documentation [page](https://doc.cuba-platform.com/manual-7.2/entity_extension.html)

If project has the Multitenancy add-on, and new entity is extending the Tenant entity the annotation could be added by Studio:
![image](https://user-images.githubusercontent.com/45730069/162707411-59ea732e-3c28-408d-a6f7-78d748f85039.png)

**Comment by knstvk** [comment]
Done, see https://docs.jmix.io/jmix/modularity/extension.html#data-model
