### ISSUE TITLE
Mention that Search add-on currently doesn't work with elasticsearch version 8.x

### ISSUE THREAD

**Issue by gorbunkov** [jmix-framework/jmix-v1-v2-docs#375]
There must be a caution on the first page of Search add-on documentation.

The issue to fix it in the framework: https://github.com/jmix-framework/jmix/issues/624

**Comment by oshiryaeva** [comment]
Already fixed in [JD-CR-73](https://upsource-platform.haulmont.com/jmix-docs/review/JD-CR-73)
