### ISSUE TITLE
Pessimistic locking

### ISSUE THREAD

**Issue by Flaurite** [jmix-framework/jmix-v1-v2-docs#387]
### Description
- `@PessimisticLock` annotation
- `LockManager`
- `StandardEditor` locks instance by default if it has annotation

See also https://github.com/jmix-framework/jmix/issues/703
Forum [discussion](https://forum.jmix.io/t/pessimistic-locking-in-jmix/1392)

**Comment by gorbunkov** [comment]
Also describe application properties introduced in the https://github.com/jmix-framework/jmix/issues/703
