### ISSUE TITLE
Provide samples how to check that user has access to entity or entity attribute

### ISSUE THREAD

**Issue by gorbunkov** [jmix-framework/jmix-v1-v2-docs#393]
There is a [section](https://docs.jmix.io/jmix/security/authorization.html#access-constraints) that briefly explains how Jmix authorization works. However, there is no example of how to check in the code that the current user has access to entity or attribute CRUD operation.

For example:

```java
CrudEntityContext crudEntityContext = new CrudEntityContext(metaClass);
accessManager.applyRegisteredConstraints(crudEntityContext);
if (!crudEntityContext.isUpdatePermitted()) {
    //...
}
```

**Comment by knstvk** [comment]
Done: https://docs.jmix.io/jmix/security/authorization.html#checking-permissions
