### ISSUE TITLE
Search not working for "MigrationHelper" string

### ISSUE THREAD

**Issue by dtaimanov** [jmix-framework/jmix-v1-v2-docs#400]
https://docs.jmix.io/jmix/cuba/index.html#webdav-migration actually contains this string
#### Steps
Open doc and type "MigrationHelper" in search field
**AR:**No results found for query "MigrationHelper"

**Comment by knstvk** [comment]
It works now at https://docs.jmix.io/1.x/jmix/1.5/cuba/index.html
