### ISSUE TITLE
Document Reports add-on

### ISSUE THREAD

**Issue by sukhova** [jmix-framework/jmix-v1-v2-docs#566]

**Comment by BryanYin** [comment]
Hi,

the report templates download URL is changed to `https://github.com/jmix-framework/jmix-samples-2/tree/main/reports-sample/src/main/resources/com/company/library/reports`, please fix the docs. Now it is `https://github.com/jmix-framework/jmix-samples-2/tree/main/library/src/main/resources/com/company/library/reports/templates` in the docs.

**Comment by sukhova** [comment]
The download URL was fixed in https://github.com/jmix-framework/jmix-docs/commit/ead182c411a18fc0df084f8e42e2682176913208
