### ISSUE TITLE
Document how to configure public path to static resources

### ISSUE THREAD

**Issue by Flaurite** [jmix-framework/jmix-v1-v2-docs#605]
### Description
See https://github.com/jmix-framework/jmix/issues/2149

See forum topic how to configure security: [forum topic](https://forum.jmix.io/t/jmix-2-0-fatjar-build-contains-reference-to-style-error/3296/13).

Example:
```
@Configuration
public class MySecurityConfiguration {

    @Bean
    @Order(JmixSecurityFilterChainOrder.FLOWUI - 10)
    public SecurityFilterChain securityFilterChain(HttpSecurity http) throws Exception {
        http.securityMatcher("/themes/**")
                .authorizeHttpRequests((authorize) -> authorize.requestMatchers("/themes/**").permitAll());
        return http.build();
    }
}
```

**Comment by knstvk** [comment]
Done in https://docs.jmix.io/jmix/security/custom-endpoints.html#custom-endpoints-security
