### ISSUE TITLE
Fix Creating Docker Image section

### ISSUE THREAD

**Issue by knstvk** [jmix-framework/jmix-v1-v2-docs#606]
A user feedback: "Creating Docker Image" is missing some params. Vaadin application is not built in production mode and gives error when trying to launch.

**Comment by Fedoseew** [comment]
In Studio we use options:` --imageName=<applicationImageName>`  and `-Pvaadin.productionMode`.
Final command example: ` ./gradlew bootBuildImage --imageName=myapp -Pvaadin.productionMode`
