### ISSUE TITLE
Warn about need of fonts installation when using Excel export actions

### ISSUE THREAD

**Issue by yuriy-khrebtov** [jmix-framework/jmix-v1-v2-docs#626]
Related issue: https://github.com/jmix-framework/jmix/issues/1107

We need to add warnings that Excel export actions (for data grid and for pivot table) require fonts properly installed on host operating system.
One particular case is when Spring Boot bootBuildImage Gradle task is used to automatically generate Docker image without Dockerfile. In this scenario OS from default base image doesn't contain fonts installed. To provide fonts to this OS a developer can, for example, configure bootBuildImage task to use another base image (full):
```
tasks.named("bootBuildImage") {
    runImage = "paketobuildpacks/run:full"
}
```
It relates both to 1.x and 2.x framework versions

**Comment by knstvk** [comment]
The following currently works fine:
```
tasks.named("bootBuildImage") {
    builder = "paketobuildpacks/builder-jammy-full"
}
```
