### ISSUE TITLE
Document how to configure anonymous access in Flow UI

### ISSUE THREAD

**Issue by Flaurite** [jmix-framework/jmix-v1-v2-docs#648]
### Description
See example based on Jmix 1.5 with FlowUI: https://forum.jmix.io/t/flow-ui-allow-anonymous-to-create-entity/3067/3
Migrated project to 2.1.2: [flowui-anonymous.zip](https://github.com/jmix-framework/jmix-docs/files/13883515/flowui-anonymous.zip)

Vaadin provides access annotations: https://vaadin.com/docs/latest/security/advanced-topics/securing-plain-java-app#access-annotations

**Comment by knstvk** [comment]
Mentioned in https://docs.jmix.io/jmix/flow-ui/views.html#common-annotations, the sample project is added to https://github.com/jmix-framework/jmix-samples-2
