### ISSUE TITLE
Update WebDAV add-on section

### ISSUE THREAD

**Issue by knstvk** [jmix-framework/jmix-v1-v2-docs#652]

**Comment by Shade30** [comment]
Also clarify the following info regarding HTTPS Configuration:

The `<base-package>` in the path to the keystore (`server.ssl.key-store` property) should be presented as a slash-separated path:
`server.ssl.key-store = classpath:com/example/demo/keystore/localhost.jks`

Also the URL in `printApplicationUrl()` method in the application class should be changed to `https://` after configuring HTTPS:
```
    @EventListener
    public void printApplicationUrl(final ApplicationStartedEvent event) {
        LoggerFactory.getLogger(DemoApplication.class).info("Application started at "
                + "https://localhost:"
                + environment.getProperty("local.server.port")
                + Strings.nullToEmpty(environment.getProperty("server.servlet.context-path")));
    }
```
