### ISSUE TITLE
Document View's methods and lifecycle events

### ISSUE THREAD

**Issue by Flaurite** [jmix-framework/jmix-v1-v2-docs#663]
### Description
See events JavaDoc for more details. Documents events:
- InitEvent
- InitEntityEvent
- BeforeShowEvent
- ReadyEvent
- ValidationEvent
- BeforeSaveEvent
- AfterSaveEvent
- BeforeCloseEvent
- AfterCloseEvent
- QueryParametersChangeEvent

Application event that is fired from StandardDetailView:
- SetupLockEvent

**Comment by knstvk** [comment]
See [internal doc](https://git.haulmont.com/platform/trainings/jmix-flowui-trainings/-/blob/main/02%20Advanced%20courses/11.%20Developing%20user%20interface%20for%20Jmix%20applications/chapters_EN/01_views.adoc)

**Comment by knstvk** [comment]
See also forum topics:
- https://forum.jmix.io/t/jmix-2-x-x-opening-dialog-windows-documentation-additional-information-needed/4417
- https://forum.jmix.io/t/instancecontainer-loading-time-differences/4744

**Comment by knstvk** [comment]
A good example: https://dev.to/pranjal-barnwal/the-journey-of-a-widget-understanding-the-lifecycle-in-flutter-3plp
