### ISSUE TITLE
Themes section

### ISSUE THREAD

**Issue by iudaev** [jmix-framework/jmix-v1-v2-docs#688]
See https://docs.jmix.io/1.x/jmix/1.5/ui/themes.html

**Comment by glebfox** [comment]
May be helpful: https://git.haulmont.com/platform/trainings/jmix-flowui-trainings/-/blob/main/02%20Advanced%20courses/11.%20Developing%20user%20interface%20for%20Jmix%20applications/chapters_EN/10_styling.adoc

**Comment by knstvk** [comment]
Done: https://docs.jmix.io/jmix/flow-ui/themes/themes.html
