### ISSUE TITLE
Improve Tooltip doc

### ISSUE THREAD

**Issue by glebfox** [jmix-framework/jmix-v1-v2-docs#692]
**Existing page:** https://docs.jmix.io/jmix/flow-ui/vc/components/tooltip.html

1. Add example of programmatic definition

2. Add more detailed description for `manual` and `opened` properties

3. Add example of programmatic opening of tooltip, specifically when it's defined in XML.

**Comment by sukhova** [comment]
Commit here: [c2202bba253f994af0790c66eec509aa6abebbdc](https://github.com/jmix-framework/jmix-docs/commit/c2202bba253f994af0790c66eec509aa6abebbdc)
