### ISSUE TITLE
Quick start remarks

### ISSUE THREAD

**Issue by skatova** [jmix-framework/jmix-v1-v2-docs#71]
1. When clicking on Creating application's data model occurs 404 Not Found page
![image](https://user-images.githubusercontent.com/53561930/108512137-39050780-72da-11eb-998f-759a28a583b4.png)

2. At the moment project id shorten automatically. Therefore this item is not relevant
![image](https://user-images.githubusercontent.com/53561930/108512578-dceeb300-72da-11eb-9b33-71a13887b6bf.png)

**Comment by owlet1997** [comment]
3. §Creating Data Model
At the moment element "On delete inverse" was renamed to "FK constraint action"
![image](https://user-images.githubusercontent.com/45730069/108593956-4bda1380-7390-11eb-929a-20635424eac0.png)
4. §Generating CRUD-screens - Screens for "Speaker" entity
At the moment caption of this screen is a 'Create Jmix Screen'
![image](https://user-images.githubusercontent.com/45730069/108594002-bdb25d00-7390-11eb-98b2-ec1beb4099bd.png)
5. §Database creation
The item in JMIX tree 'Generic UI' was renamed to 'Backoffice UI':
![image](https://user-images.githubusercontent.com/45730069/108594061-20a3f400-7391-11eb-9eb3-b61f4bcfcd8b.png)
6. §Adding Business Logic
When clicking on "Using screen API" occurs 404 Not Found page:
![image](https://user-images.githubusercontent.com/45730069/108594133-88f2d580-7391-11eb-9533-b66001bd3182.png)
7. §Adding Branding
The item in JMIX tree 'Generic UI' was renamed to 'Backoffice UI':
![image](https://user-images.githubusercontent.com/45730069/108594231-19311a80-7392-11eb-8584-9a4eccb4ece2.png)

**Comment by zhenyazb** [comment]
Fixed in #75
