### ISSUE TITLE
Studio: migrate Upgrading a Project section

### ISSUE THREAD

**Issue by alexbudarov** [jmix-framework/jmix-v1-v2-docs#78]
from: https://doc.cuba-platform.com/studio/#upgrade_project

- Adapt to change in Jmix Studio UI. (e.g. Jmix tool window -> toolbar -> Settings -> Project Properties instead of CUBA -> Project Properties).

- outdated info:
> If your project includes CUBA Add-ons, you may need to update them to the appropriate version compatible with the new CUBA platform version

This isn't true anymore for addons created by core team. Upgrading addons manually will be necessary only for community addons.

**Comment by alexbudarov** [comment]
On hold until release 1.1 (otherwise we can't screenshot release notes links, migration links etc.)

**Comment by zhenyazb** [comment]
fixed in #290
