### ISSUE TITLE
Remove deprecated code in the UI integration Tests section

### ISSUE THREAD

**Issue by Flaurite** [jmix-framework/jmix-v1-v2-docs#781]
### Description
The page: https://docs.jmix.io/jmix/testing/ui-integration-tests.html

See the cause of deprecation: https://github.com/jmix-framework/jmix/issues/3157
Since the https://github.com/jmix-framework/jmix/issues/3350 tests works with both the deprecated method and the new one.

#### What should be fixed
From
```
viewNavigators.view(UserListView.class).navigate();
```
To
```
viewNavigators.view(UiTestUtils.getCurrentView(), UserListView.class).navigate();
```

**Comment by knstvk** [comment]
Done
