### ISSUE TITLE
New REST-services development use cases

### ISSUE THREAD

**Issue by syncro** [jmix-framework/jmix-v1-v2-docs#784]
More REST-service development details should be described in documentation: 

* How to use new (starting from 2.3) @RestSerivce and @RestMethod annotations
* How to implement pulicitly(anonymous) available endpoints (incl. necessary security configurations)
* How Spring @RestController and OpenAPI addons can be composed with jmix

**Comment by knstvk** [comment]
Here: https://docs.jmix.io/jmix/rest/business-logic.html
