### ISSUE TITLE
Describe reliable way to navigate between views on action

### ISSUE THREAD

**Issue by syncro** [jmix-framework/jmix-v1-v2-docs#795]
Current api hints says the way described in docs became deprecated starting from 2.3

![image](https://github.com/jmix-framework/jmix-docs/assets/195749/44ffba25-ba12-423c-b366-0fff3e892ddf)

ViewNavigators has methods with addictional origin argument, but I can not figure out what should be passed. Tried this pointer of current view, but this causes runtime error

**Comment by knstvk** [comment]
Done: https://docs.jmix.io/jmix/flow-ui/views/opening-views.html#navigation
