### ISSUE TITLE
Document DdlGeneration and DbView annotations

### ISSUE THREAD

**Issue by alexbudarov** [jmix-framework/jmix-v1-v2-docs#82]
Document entity annotations used by Studio:
- io.jmix.data.DdlGeneration
- io.jmix.data.DbView

see forum topic: https://www.cuba-platform.ru/discuss/t/chtenie-dannyh-iz-predstavlenij-bazy-dannyh-database-view/5452/4

**Comment by HUO-Zhaoheng** [comment]
Could you please give an example? I have try annotate my class with DbView, but liquibase does nothing.

**Comment by alexbudarov** [comment]
That's correct, classes annotated with DbView should be ignored. Did you want Liquibase to create a database view?
