### ISSUE TITLE
Document partNameGenerator and make changes with classNameGenerator issue

### ISSUE THREAD

**Issue by fractal3000** [jmix-framework/jmix-v1-v2-docs#848]
Information about partNameGenerator is absend in our documentation(link below) so it shoud be added to the page
https://docs.jmix.io/jmix/2.2/flow-ui/vc/components/dataGrid.html
But information about classNameGenerator should be brought into line(deleted or corrected) with changes of the issue
https://github.com/jmix-framework/jmix/issues/3515

**Comment by knstvk** [comment]
Done: https://docs.jmix.io/jmix/flow-ui/vc/components/treeDataGrid.html#partNameGenerator
