### ISSUE TITLE
Describe jmix.gridexport.export-all-pagination-strategy configuration parameter

### ISSUE THREAD

**Issue by syncro** [jmix-framework/jmix-v1-v2-docs#895]
Important configuration parameter must be described in documentation

`
jmix.gridexport.export-all-pagination-strategy=limit-offset
`

https://docs.jmix.ru/jmix/grid-export/properties.html

https://docs.jmix.io/jmix/grid-export/properties.html

Introduced in https://github.com/jmix-framework/jmix/issues/3001

**Comment by knstvk** [comment]
Also change `jmix.gridexport.exportAllBatchSize` to kebab-case.
