### ISSUE TITLE
Add direct links between topics of Jmix documentation from version 1 to latest version

### ISSUE THREAD

**Issue by gmmars** [jmix-framework/jmix-v1-v2-docs#897]
At the moment version 1 of Jmix documentation is well indexed by search engines and therefore most google search results lead to the old version of the documentation. When Jmix site offers to go to the updated version it will lead to the main page and you have to start your search again.
It would be very helpfull if old version will lead to the same topic in the new version when it exists.

**Comment by knstvk** [comment]
The "Go to the latest version" link goes to a page matching by name. Also, `ui` is replaced with `flow-ui`.
If the matching page doesn't exists, the link goes to the root.
