### ISSUE TITLE
REST API documentation

### ISSUE THREAD

**Issue by gmmars** [jmix-framework/jmix-v1-v2-docs#907]
1. In generated docs fetchPlan is marked as boolean, although according to description it is required to pass name fetchPlan
![image](https://github.com/user-attachments/assets/f42bdc83-2baa-4bd5-ae03-483867c424b8)

2. In generated docs /rest/docs/openapiDetailed.json on /{entityName}/search for POST.  It is said that fetchPlan, limit and etc. 
are the request parameters, and in Request body only filter definition. Although indeed filter, fetchPlan, limit and etc. should all be in Request body.

**Comment by Gavrilov-Ivan** [comment]
Move to Jmix framework
