### ISSUE TITLE
Studio: migrate Working with Entities section

### ISSUE THREAD

**Issue by alexbudarov** [jmix-framework/jmix-v1-v2-docs#98]
From: https://doc.cuba-platform.com/studio/#data_model_entities

To: I think we should create sub-page of the https://docs.jmix.io/jmix/0.x/data-model/entities.html article.
Add link from Tool Window to this new section.

That section is totally incomplete.
But let's migrate it as is, just adapting to Jmix.
In Jmix there are significant changes in creation dialog, actions (create DTO entity, create JPA entity).

**Comment by zhenyazb** [comment]
fixed in #361
